pipeline:  
  add-repo:
    image: omerxx/drone-secret-deployer
    pull: true
    drone_server: https://droneio.spot.im
    action: add
    when:
      branch: develop


  docker-publish:
    image: plugins/docker
    repo: omerxx/drone-lambda-secret-injection
    tag:
      - ${DRONE_BUILD_NUMBER}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
