pipeline:  
  add-repo:
    image: omerxx/drone-secret-deployer:test
    drone_server: https://droneio.spot.im
    action: add
    secrets: 
      - source: drone_token
        target: plugin_drone_token
    when:
      branch: develop

  docker-publish:
    image: plugins/docker
    repo: omerxx/drone-lambda-secret-injection
    tag:
      - ${DRONE_BUILD_NUMBER}
      - latest
    secrets: [ docker_username, docker_password ]
    when:
      branch: [master]
